name: flutter_hls_parser_example
description: Demonstrates how to use the flutter_hls_parser plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_hls_parser:
    path: ../
flutter:
  uses-material-design: true
