name: flutter_hls_parser
description: dart plugin for parse m3u8 file for HLS. both of master and media file is supported.
version: 1.0.0
author: Hiroyuki Tamura <hiroyuktamura@gmail.com>
homepage: https://github.com/HiroyukTamura

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.cks.flutter_hls_parser
    pluginClass: FlutterHlsParserPlugin
